FROM quay.io/keycloak/keycloak:21.1.1

# Set environment variables
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=Anjesh@123
ENV KC_PROXY=edge
ENV KC_HTTP_ENABLED=true
ENV KC_HOSTNAME_STRICT=false
ENV KC_DB=dev-file

# Build Keycloak
RUN /opt/keycloak/bin/kc.sh build

# Expose port (Render uses PORT env var, but Keycloak defaults to 8080)
EXPOSE 8080

# Start Keycloak
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start", "--optimized", "--http-port=8080"]